### ISSUE TITLE
pixijs externs

### ISSUE THREAD

**Issue by adireddy** [damoebius/haxe-npm#10]
Hi @damoebius, can you please update `pixijs` externs to https://github.com/pixijs/pixi-haxe

**Comment by damoebius** [comment]
Hi :)
I'm going to update pixijs externs

**Comment by adireddy** [comment]
:+1:

**Comment by damoebius** [comment]
you can try the new release 0.320.10.
Tell me if this is good for pixijs

**Comment by adireddy** [comment]
looks good... thx @damoebius :)
