### ISSUE TITLE
Is haxelib supported locally ?

### ISSUE THREAD

**Issue by erixtekila** [damoebius/haxe-npm#2]
Once haxe is installed from npm locally, will the haxelib too ?

**Comment by damoebius** [comment]
No.
You should consider NPM as a haxelib replacement.
All externs will be progressively integrated into this package but if you need others libs, It will be necessary integrate them in npm.

Contact me by email to talk in french about it :-)

**Comment by erixtekila** [comment]
Bonjour David,

Est-ce cet email que tu utilises ?

Quelques précisions par rapport à haxe npm seraient les bienvenues.
Quel workflow est envisagé ?

Merci
Le 30 mai 2014 à 17:10, damoebius notifications@github.com a écrit :

> No.
> You should consider NPM as a haxelib replacement.
> All externs will be progressively integrated into this package but if you need others libs, It will be necessary integrate them in npm.
> 
> Contact me by email to talk in french about it :-)
> 
> —
> Reply to this email directly or view it on GitHub.

---

Eric Priou aka erixtekila
http://www.ericpriou.net
