### ISSUE TITLE
NPM package not working?

### ISSUE THREAD

**Issue by dionjwa** [damoebius/haxe-npm#3]
![image](https://cloud.githubusercontent.com/assets/260221/6051222/0cf27c4e-ac7b-11e4-8c91-dbc74131847f.png)

In this npm package working?

**Comment by dionjwa** [comment]
For: https://www.npmjs.com/package/haxe

**Comment by damoebius** [comment]
yes, it works perfectly.
I have just broken the readme.md file
it's fixed
