### ISSUE TITLE
Failure to run after installation

### ISSUE THREAD

**Issue by dionjwa** [damoebius/haxe-npm#4]
On an Ubuntu virtual image, I get this error when I run haxe:

```
: No such file or directory
```

This occurs regardless if I install locally with 

```
npm install haxe
```

or globally with 

```
sudo npm install -g haxe
```

**Comment by dmouton** [comment]
Damned you are right.
There is a probleme with /usr/local/lib/node_modules/haxe/bin/haxe-cli.js 
#!/usr/bin/env node doesn't work and i don't know why !!!
BTW be sure to have installed node-legacy under linux ( apt-get install nodejs-legacy )
I'm on it

**Comment by dmouton** [comment]
It seems that i have to publish from linux
try the news release 0.1.25
sudo npm install -g haxe

**Comment by dionjwa** [comment]
Ok, that works. But haxelib doesn't. There's no npm haxelib package? Or it's not packaged with this package?

**Comment by damoebius** [comment]
Haxelib is another packet manager. Why do you want use it ?

**Comment by dionjwa** [comment]
Oh, I see. You package all the haxe packages with npm. Nevermind.
