### ISSUE TITLE
Simplify this package

### ISSUE THREAD

**Issue by clemos** [damoebius/haxe-npm#5]
Hi,
I'd very much like to use / promote your npm (through https://github.com/clemos/haxe-js-kit and https://github.com/clemos/generator-haxe-webapp), and possibly contribute and help you maintain it.
But I feel it should be simplified; mainly, I think it shouldn't include third parties, only the compiler.
Also, what's the plan in terms of releases ? Can you follow haxe releases "automatically" ?

**Comment by damoebius** [comment]
Agree, we will talk about the roadmap at wwx2015

**Comment by clemos** [comment]
Hey David,
I was working back on the topic.
As discussed, I still think the externs should be removed from this NPM package.
What do you think ?
If you want, I can make a PR to remove them, but you probably want to put them somewhere else ;)
Cheers

**Comment by damoebius** [comment]
There is about 100 haxe packages on npm now, so we can clean this one.
I give you push access to this repo

**Comment by lexoyo** [comment]
Hi
Same interest here, this is great to have haxe on npm with versions following the compiler versions.

How can I help, maybe remove the lib folder to get started? 

Should the `template/` folder stay?

What is `std/` for?

**Comment by damoebius** [comment]
Hi Alex, you have an access too.
You can remove the /lib and /template directory but if you do that, don't forget to remove -use and -create support in haxe-cli.js

/std is for the haxe std lib

**Comment by lexoyo** [comment]
With @clemos we are talking about this
- do not store the compiled version of haxe in bin, but download the version corresponding to the version in package.json
- support haxelib like it supports haxe (download the executable)

And we talked about how we could avoid to require neko (if it is a good idea, this is to discuss further), maybe by compiling neko on postinstall, or even compile haxelib in C

**Comment by damoebius** [comment]
Downloading binaries sounds good :-) 
But i'm not sure for haxelib...
We can work on a clean release and look for haxelib after that

**Comment by clemos** [comment]
FYI I started something from scratch, to try and make the package as simple as possible:
https://github.com/clemos/npm-haxe
It's still very rough (untested on Mac or Windows),
but feel free to give it a try and provide feedback ;)

**Comment by fullofcaffeine** [comment]
I never really got the point of this project (don't want to sound harsh, not the intention, so bear with me!) -- What does this project have that haxe-js-kit doesn't? What are the use cases?

**Comment by damoebius** [comment]
Have a look on this : https://prezi.com/m/gwjzktjor3zf/npm-haxe-at-the-heart-of-javascript-ecosystem/
Our goal is to use haxe from npm as typescript, cofeescript, etc...

**Comment by damoebius** [comment]
And this https://m.youtube.com/watch?v=YgbxqFx9qak

**Comment by dmouton** [comment]
Hi @clemos , can you test this new release ?
I update this project with a part of your work.

**Comment by clemos** [comment]
Hi @damoebius 
I reviewed your commit, your changes seem to go in the right direction (IMHO) ;)
I'll test it on a real world project next year :D

**Comment by damoebius** [comment]
@clemos Is it working ?

**Comment by clemos** [comment]
Sorry, I haven't had the chance to test it yet.
Also, I need sandboxed haxelib, and I don't think your package supports it, does it ?

**Comment by damoebius** [comment]
There's no haxelib support, only npm libs

**Comment by damoebius** [comment]
I published it on npm
