### ISSUE TITLE
Local run error on Debian

### ISSUE THREAD

**Issue by fantoine** [damoebius/haxe-npm#6]
I'm trying to use it as a local dev dependency on a Debian but when I get the following error:

```
{ [Error: Command failed: /project/node_modules/haxe/bin/haxe.bin: 5: /project/node_modules/haxe/bin/haxe.bin: Syntax error: "(" unexpected
] killed: false, code: 2, signal: null }
```

I use the following command to run it

``` shell
./node_modules/./bin/haxe
```

Any idea to fix it?

**Comment by damoebius** [comment]
I'm working on it

**Comment by damoebius** [comment]
It should be better now.
Tell me if it's ok for you
