### ISSUE TITLE
Bloody o' windows carriage return char on *nix

### ISSUE THREAD

**Issue by erixtekila** [damoebius/haxe-npm#8]
Unfortunatly, haxe-cli.js generates a launch error on *nix system.
Modifying the carriage return do the trick.

How could one produce TRUE crossplatform nodejs script ?

**Comment by damoebius** [comment]
Arg, i make this package on windows and it corrupted carriage code.
There is a new release 0.320.9, maked on linux. 
It works on both windows and linux.
Could you tell me if it's good for you now ?

**Comment by erixtekila** [comment]
Work well. Thanks.
